apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yml
  - cloudnative-pg.yml
  - kube-state-metrics.yml
  - local-path-provisioner.yml
  - metallb.yml
  - nfs-csi.yml
  - node-exporter.yml
  - prometheus-operator.yml
  - reloader.yml
  - sealed-secrets.yml
  - traefik.yml