apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: prometheus-operator
      app.kubernetes.io/component: prometheus
resources:
  - rbac.yml
  - prometheus.yml
  - service.yml
  - ingress.yml
  - monitor.yml