apiVersion: v1
kind: Service
metadata:
  name: prometheus
  annotations:
    metallb.io/loadBalancerIPs: 10.1.1.4
spec:
  selector:
    prometheus: prometheus
  ports:
    - name: web
      port: 9090
      targetPort: web