apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: local-path-provisioner
    includeTemplates: true
    includeSelectors: true
resources:
  - rbac.yml
  - network-policy.yml
  - config-map.yml
  - deployment.yml
  - storage-class.yml