---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth-credentials
  namespace: traefik-system
spec:
  encryptedData:
    password: AgDC/CGC1vDt6P+jS5iiBWG7FeCVczjgrI3I97siMMcZFG+xvmrx2kCp+0BDnqAAzgXU3LOPK145fEPru+hpEv+z7lnNkqTYcZi8ISccLXvoRsSPUkEnMPyB2HQPzeEZCRNvv5pvZ+YlVO+B9K/RsGGwLiKbL8L88Usk0p2rgXWA3BmPGZv6XhncLXVyLapY5+1HEyLjyqDm0JFycwbSECaOFR8A0Slz+J+j9FDtd3GKksI1oM1NxX26b+QhU9DBBYwqXzxBGktoUvTj4EtVPXYK3rlVHkmVxDmLfYh3mKFSii6Nikot507kRdgO63VIR2kmscnVeeI7Xk8n85woDlpr2XxvGTaEowZc714m8WpI9ibumDnwmkL+j8s1XmaFMYoZMzYrAMG7vN6K2R7qrHMeorFU4UeoK7AMaoduoJUFymjjUCnj8TDY3eJcwOvcquu+Ycii3SthSk8pTEn1SE0XL4tH53K7gbtLzCWjSRdy2WWRirAvIXqOhkTvvIrskixlPYW0LC18/5IBi2HvWUwaMa+3u2fzOaB6QrAneU5ODDKWQBlEKHGpuy8DRo4tZs5LmDMJ5GPqcr3m3JkxbcW0rLcVPwYkHM9rCrGPa7bVfvebTU6SIDDCKv0c1eeeHTe3Vg5FDvPs/vvO27VrxzyEuQ2mv7um0jq270iZWWARHQYLtYlB2eMS+wmd9x70jeng/ST5EyPHWdwkEkqy1CHJ
    username: AgCBvEPktSn6gmimlNRn2kTz9opIfbosVghnwa4tydW87/Jy6iUc1lKwY4j6uvHFIODJSiDEWyIlek/IdyFdiAjCDR2sueeVzhJPP9RLl3HOt1D/xGo96Ltebp6BurC/IRsTtEubILfe1S45g4jOu3QbdKhTtrTCets686ejgcKyGCW3cAvkXHapqjKMpDFGIzscIctlqqSANIGHOSFSyPyoU3s2QqKgI6dy9XOF+rpH4P+Kl+Wn/D3dAz/u48NnAfAdzk7GjjRpa/l7TQJLqzrv04PTACaRq2V/Il4UrWntco2X29doTvjRkhTL+paXxxxoVp64zLevlWPe2Iu6rE+ru9um3Mrv4siOfBZRKYw+4orKBG7CNRbk6qPB59Qw2PK3vdUpLQQAPqVp91W8OadLUf6BAcw8quuA4IaQhTUfQb4YjXgSPQqZY0DEq9sRgV+JNfZlOuwDv4PO1Sv992NaOBJld2jnC17q3d919whg4PXIzNPXQ8+1IdFUtU1WGdlFgFD7UCG7Su3FnlzkqJJ5UCAlCL2hR2xJk7IguUhLEGV11eNmaFXEeur84fEq7XKElB3ntoAwVpOIEOHaAVddK60uOOdui8M27zNvTU1Q30lXPHo6XTwP0WTXUlfwWe5XKjJ/3OeE/HEsb0Av09njDw7AR6wHLcCy7Ap45ZNlPJJ0mk+voKZNgtZBG6mPu7NUHnW6MQ==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: traefik
      name: basic-auth-credentials
      namespace: traefik-system
    type: kubernetes.io/basic-auth
