apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: prometheus-operator
      app.kubernetes.io/component: controller
    includeTemplates: true
    includeSelectors: true
resources:
  - network-policy.yml
  - rbac.yml
  - deployment.yml
  - service.yml